### ISSUE TITLE
Request: ability to hide / show reputations

### ISSUE THREAD

**Issue by TrueOsiris** [Eliote/TitanReputation#3]
Hi! First of all: thanks so much for this addon. Have been missing this badly.
This is not really an issue, but a dev request.
It would be cool if we could hide/show certain reputations in that list. (e.g. Show only TBC relevant reputations)

**Comment by Eliote** [comment]
Hello, sorry for the late response. You can actually "kinda" do that using the reputation window from blizzard. If you minimize an expansion there, it should disappear from the tooltip too.
I'm really busy at work and not really playing wow. So I'll close this for now and reopen it if I find some time to do something better.
Thanks! :)
